export const USERACTIONS = {
    REGISTER: 'REGISTER',
    LOGIN: 'LOGIN',
    HISTORY: 'HISTORY',
    SHOW_CART: 'SHOW_CART',
    CLOSE_CART: 'CLOSE_CART',
    SHOW_AUTHEN_FORM: 'SHOW_AUTHEN_FORM',
    CLOSE_AUTHEN_FORM: 'CLOSE_AUTHEN_FORM',
    LOGOUT: 'LOGOUT',
    CLEAR_CART: 'CLEAR_CART',
    ADD_ORDER: 'ADD_ORDER',
    CHANGE_CURRENCY: 'CHANGE_CURRENCY'
}

export const ORDERACTIONS = {
    ORDER: 'ORDER',
    PAYMENT : 'PAYMENT',
    BOOK: 'BOOK',
    REMOVEBOOK: 'REMOVEBOOK',
    REMOVEITEMBOOK: 'REMOVEALLITEMBOOK'
}

export const ITEMACTIONS = {
    ALLPIZZA: 'ALLPIZZA',
    PIZZA: 'PIZZA'
}